server:
  port: 8081
logging:
  level:
    root: info
    com.rory: debug

service:
  user:
    path: http://localhost:8080/simple/users/
eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
spring:
  application:
    name: micro-user-service-consumer
