server:
  port: 8087
spring:
  application:
    name: micro-user-service-feign
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:8761/eureka
